export const STORY_PARAGRAPHS = [
  "If I'm being honest, I had absolutely no idea what I was doing when I started my undergraduate degree. I couldn't even draw a straight line. I wasn't the person who had been making art since childhood or filling sketchbooks every day. Everything started from zero.",
  "I just became... curious.",
  "Once I got into university, I wanted to try everything. Every new software, every project, every technique—I wanted to know how it worked. There were nights where I'd stay in the studio until early morning with my lecturers and classmates, sculpting characters, building environments, trying things over and over again. Those moments are still some of my favourite memories because that's where I realised I genuinely loved creating in 3D.",
  "But even after finishing my degree, something didn't feel finished.",
  "It felt like there was still so much I didn't know.",
  "That's why I decided to come to the UK and continue studying. I wanted to put myself in a completely different environment, meet new people, learn new ways of working, and see how much further I could push myself. That's also where I found a new curiosity—photogrammetry and reality capture. Seeing the real world become something digital completely changed the way I looked at creating environments.",
  "I'm not going to pretend it's been easy.",
  "Balancing a Master's degree while working part-time just to support myself has probably been one of the hardest things I've done. There were weeks where I questioned whether I could keep up. Sometimes work took away the time I wanted to spend creating, and that was frustrating.",
  "But one thing never really disappeared.",
  "My curiosity.",
  "I still get excited about learning something I've never done before. Whether that's experimenting with AI to build this website, learning a new workflow in Unreal Engine, figuring out photogrammetry, or breaking something just to understand why it works—I genuinely enjoy that process.",
  "And if there's one thing I'm proud of, it's probably not my best render or my favourite project.",
  "It's my failures.",
  "Every project in this portfolio has something that went wrong. Some didn't turn out the way I imagined. Some took far longer than they should have. Some made me completely rethink my approach. But every single one taught me something I still use today.",
  "I don't really believe failure is the opposite of success.",
  "For me, it's just part of learning.",
  "Looking back, I think that's been the one thing that's stayed with me from the beginning. I might not have started with experience, but I've always been willing to learn, ask questions, experiment, fail, and try again.",
  "And honestly...",
  "The more I learn, the more I realise how much I still don't know.",
  "There are still more environments I want to build, more technologies I want to explore, more people I want to learn from, and more ideas I want to bring to life.",
  "I don't think that curiosity is ever going away.",
] as const;
